### Register Post Request
POST http://localhost:8000/api/register
Content-Type: application/json

{
    "name": "test",
    "email": "yours@example.com",
    "password": "12345"
}

### Login Post Request
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email": "yours@example.com",
    "password": "12345"
}

################################################################
######## Survey
################################################################

### Get All Survey
GET http://localhost:8000/api/Survey